version: 2

models:
    - name: int_local_bike__order_items
      description: "This table contains enhanced informations about each item of specific order."
      columns:
          - name: order_product_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: int_local_bike__stocks
      description: "This table contains enhanced informations about each product stocks in the stores."
      columns:
          - name: order_product_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
